import ArgumentParser
import Foundation
import Logging
import ManagedRelayCore

@main
struct SloppyRelayCommand: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "SloppyRelay",
        abstract: "Run and administer the managed Sloppy relay.",
        subcommands: [
            RelayServeCommand.self,
            RelayBootstrapAdminCommand.self,
            RelayCreateInviteCommand.self,
        ],
        defaultSubcommand: RelayServeCommand.self
    )
}

private struct RelayDatabaseOptions: ParsableArguments {
    @Option(help: "PostgreSQL connection URL (local development only; visible in process arguments).")
    var databaseURL: String?

    @Option(help: "Path to a file containing the PostgreSQL connection URL.")
    var databaseURLFile: String?

    func makeStore() throws -> ManagedRelayPostgresStore {
        guard (databaseURL == nil) != (databaseURLFile == nil) else {
            throw ValidationError("Provide exactly one of --database-url or --database-url-file")
        }
        let rawURL = try databaseURLFile.map {
            try String(contentsOfFile: $0, encoding: .utf8)
                .trimmingCharacters(in: .whitespacesAndNewlines)
        } ?? databaseURL ?? ""
        guard let url = URL(string: rawURL),
              url.scheme == "postgres" || url.scheme == "postgresql" else {
            throw ValidationError("--database-url must be a PostgreSQL URL")
        }
        let pepperText = try ProcessInfo.processInfo.environment["SLOPPY_RELAY_PEPPER_FILE"].map {
            try String(contentsOfFile: $0, encoding: .utf8)
                .trimmingCharacters(in: .whitespacesAndNewlines)
        } ?? ProcessInfo.processInfo.environment["SLOPPY_RELAY_PEPPER"]
        guard let pepperText,
              let pepper = Data(base64Encoded: pepperText), pepper.count >= 32 else {
            throw ValidationError("SLOPPY_RELAY_PEPPER must be at least 32 random bytes in base64")
        }
        return try ManagedRelayPostgresStore(
            databaseURL: url,
            pepper: pepper,
            logger: Logger(label: "sloppy.managed-relay.db")
        )
    }
}

private struct RelayServeCommand: AsyncParsableCommand {
    static let configuration = CommandConfiguration(commandName: "serve")

    @OptionGroup var database: RelayDatabaseOptions

    @Option(help: "Public HTTPS URL advertised to clients.")
    var publicURL: String

    @Option(help: "Private HTTP bind address behind the TLS reverse proxy.")
    var host: String = "127.0.0.1"

    @Option(help: "Private HTTP listen port.")
    var port: Int = 25111

    mutating func run() async throws {
        guard let publicEndpoint = URL(string: publicURL),
              publicEndpoint.scheme == "https" else {
            throw ValidationError("--public-url must use HTTPS")
        }
        let store = try database.makeStore()
        let coordinator = ManagedRelayCoordinator(store: store, publicURL: publicEndpoint)
        let databaseTask = Task { await store.client.run() }
        defer { databaseTask.cancel() }
        try await store.migrate()
        let router = RelayHTTPRouter(coordinator: coordinator, store: store, publicURL: publicEndpoint)
        let server = RelayHTTPServer(host: host, port: port, router: router, coordinator: coordinator)
        try server.start()
        Logger(label: "sloppy.managed-relay").info("Managed relay listening on private port \(port)")
        try server.wait()
    }
}

private struct RelayBootstrapAdminCommand: AsyncParsableCommand {
    static let configuration = CommandConfiguration(commandName: "bootstrap-admin")

    @OptionGroup var database: RelayDatabaseOptions

    @Option(help: "Base64 Ed25519 public key generated by the admin browser.")
    var publicKey: String

    @Option(help: "Admin device display name.")
    var name: String = "Relay Admin"

    mutating func run() async throws {
        guard let key = Data(base64Encoded: publicKey), key.count == 32 else {
            throw ValidationError("--public-key must be a base64 Ed25519 public key")
        }
        let store = try database.makeStore()
        let databaseTask = Task { await store.client.run() }
        defer { databaseTask.cancel() }
        try await store.migrate()
        let id = try await store.bootstrapAdminDevice(publicKey: key, name: name)
        print(id.uuidString)
    }
}

private struct RelayCreateInviteCommand: AsyncParsableCommand {
    static let configuration = CommandConfiguration(commandName: "invite-create")

    @OptionGroup var database: RelayDatabaseOptions

    @Option(help: "Registered admin device UUID.")
    var adminDeviceID: String

    @Option(help: "Invite lifetime in minutes (1...1440).")
    var ttlMinutes: Int = 60

    mutating func run() async throws {
        guard let adminID = UUID(uuidString: adminDeviceID),
              (1...1440).contains(ttlMinutes) else {
            throw ValidationError("Provide a valid admin UUID and TTL from 1 to 1440 minutes")
        }
        let store = try database.makeStore()
        let databaseTask = Task { await store.client.run() }
        defer { databaseTask.cancel() }
        try await store.migrate()
        let invite = try await store.createServiceInvite(
            adminDeviceID: adminID,
            expiresAt: Date().addingTimeInterval(Double(ttlMinutes * 60))
        )
        print(invite)
    }
}
